/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OpAppHeader {
    }
}
declare global {
    interface HTMLOpAppHeaderElement extends Components.OpAppHeader, HTMLStencilElement {
    }
    var HTMLOpAppHeaderElement: {
        prototype: HTMLOpAppHeaderElement;
        new (): HTMLOpAppHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "op-app-header": HTMLOpAppHeaderElement;
    }
}
declare namespace LocalJSX {
    interface OpAppHeader {
    }
    interface IntrinsicElements {
        "op-app-header": OpAppHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "op-app-header": LocalJSX.OpAppHeader & JSXBase.HTMLAttributes<HTMLOpAppHeaderElement>;
        }
    }
}
